# Generated by Selenium IDE
from operator import index

import time
import json
import base64
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
# Importar a classe que contém as funções e aplicar um alias
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.action_chains import ActionChains
import requests
import urllib.parse

def resert():
    index()
def getCodigoPasta(elementos, foro):
    for precatoria in elementos:
        if (precatoria.text == "Precatório - 0" + foro[1]):
            link = precatoria.get_attribute('href')
            return link
def index():
    error = 0
    driver = webdriver.PhantomJS()
    #driver = webdriver.Chrome()
    wait = WebDriverWait(driver, 5)
    actions = ActionChains(driver)
    try:
        driver.get("https://esaj.tjsp.jus.br/sajcas/login")
        driver.find_element(By.ID, "usernameForm").click()
        driver.find_element(By.ID, "usernameForm").send_keys("967.933.923-87")
        driver.find_element(By.ID, "passwordForm").click()
        driver.find_element(By.ID, "passwordForm").send_keys("arthur149511")
        driver.find_element(By.ID, "pbEntrar").click()
        driver.get("https://esaj.tjsp.jus.br/cpopg/open.do?gateway=true")
        urlAtual2 = driver.current_url
        print("Aguardando Resposta do Servidor com os Processos!")
        print(urlAtual2)
        capturarCdProcesso2 = urlAtual2.split("gateway")
        print(capturarCdProcesso2)
        cdProcesso2 = capturarCdProcesso2[1].split("=")
        #print("Codigo Processo:" + processo.codigo[0])
        print(cdProcesso2[1])
    except:
        print('Erro: => Error de Conexão')
        driver.quit()
        index()
    getProcessos = requests.get('https://www.fairconsultoria.com.br/v1/process')
    if(getProcessos.status_code == 200):
        print("Capturados!")
        processosCapturados = getProcessos.json()
        for processos in processosCapturados["data"]:
            novaJanela = 0
            print("Capturando Informaçãoes do Processo:"+ processos['processo_de_origem'])
            try:
                removeEspacos = processos['processo_de_origem'].strip()
                numeroProcesso = removeEspacos.split('.')
                driver.find_element(By.ID, "numeroDigitoAnoUnificado").click()
                driver.find_element(By.ID, "numeroDigitoAnoUnificado").send_keys(numeroProcesso[0]+"."+numeroProcesso[1])
                driver.find_element(By.ID, "foroNumeroUnificado").click()
                foro = numeroProcesso[4].split("/")
                driver.find_element(By.ID, "foroNumeroUnificado").send_keys(foro[0])
                driver.find_element(By.ID, "botaoConsultarProcessos").click()
                try:
                    try:
                        try:
                            driver.find_element(By.LINK_TEXT,numeroProcesso[0] + "." + numeroProcesso[1] + ".8.26." + foro[0]).click()
                        except:
                            print('Procurando novamente')
                        elementos = driver.find_elements(By.CLASS_NAME,"incidente")
                        link = getCodigoPasta(elementos, foro)
                        print(link)
                        driver.get(link)
                        capturarCdProcesso = link.split("processo.codigo=")
                        cdProcessoPasta = capturarCdProcesso[1].split("&")
                        driver.execute_script("window.open('https://esaj.tjsp.jus.br/cpopg/abrirPastaDigital.do?processo.codigo="+cdProcessoPasta[0]+"', '_blank')")
                        time.sleep(5)
                        novaJanela = 1
                        driver.switch_to.window(driver.window_handles[1])
                        time.sleep(5)
                        urlAtual = driver.current_url
                        print("Procurando Codigo do processo!")
                        print("Codigo Processo:" + cdProcessoPasta[0])
                        driver.find_element(By.LINK_TEXT, "Termo de Declaração").click()
                        print("Procurando PDF Correto!")
                        time.sleep(3)
                        urlPdf = urllib.parse.unquote(driver.find_element(By.ID, "documento").get_property('src'))
                        novoUrlPdf = urlPdf.split("getPDF.do?")
                        codUrl = base64.b64encode(novoUrlPdf[1].encode('utf-8'))
                        print("Pdf encontrado e capturado!")
                        print("Atualizando Processo no Servidor!")
                        driver.get('https://fairconsultoria.com.br/v1/process/update/%i/%s/%s' % (
                        processos["id"],cdProcessoPasta[0], codUrl.decode('utf-8')))
                        time.sleep(5)
                        print("Processo Atualizado")
                        driver.close()
                        driver.switch_to.window(driver.window_handles[-1])
                    except Exception as e:
                        print("Error: => Precatorio não encontrado")
                        print(e)
                        actions.key_down(Keys.ESCAPE)
                        actions.key_up(Keys.ESCAPE)
                        actions.perform()
                        if (novaJanela == 1):
                           driver.close()
                           time.sleep(3)
                        driver.switch_to.window(driver.window_handles[-1])
                    time.sleep(2)
                except:
                    time.sleep(5)
                    print('Parei aqui')
                    actions.key_down(Keys.ESCAPE)
                    actions.key_up(Keys.ESCAPE)
                    actions.perform()
                time.sleep(3)
                driver.find_element(By.ID, "numeroDigitoAnoUnificado").clear()
                driver.find_element(By.ID, "foroNumeroUnificado").clear()
            except:
                driver.get('https://esaj.tjsp.jus.br/cpopg/open.do')

        time.sleep(120)
        resert()
    else:
        print('Error: => Erro ao capturar os processos do servidor')
        print('Tentando novamente')
        error =+ 1
        if(error > 3):
            time.sleep(60)
            resert()

index()